### PR TITLE
Move frontend updates to celery task

### PR DESCRIPTION
**Pull request by erikh360**

### CODE REVIEW

**Comment by nathanbegbie** [comment]
@erikh360 is this a slow task? I'm just wondering what the benefits of making this async are/using celery?

**Comment by erikh360** [comment]
@nathanbegbie We're also going to be sending out messages to a WA group in the `PostPatientUpdate` task. So this is just the first step in that. I should have mentioned this in the description.

**Comment by nathanbegbie** [comment]
@erikh360 ah, okay that makes this clearer. Could you also add a health check, if we're going to be using RabbitMQ, similar to [this PR](https://github.com/praekeltfoundation/rp-sidekick/pull/66)?

**Comment by erikh360** [comment]
@nathanbegbie good idea, I'll do it in a separate PR though.

**Comment by nathanbegbie** [comment]
Okidokes 👍

**Pull request merged**
