### PR TITLE
Feature/add anesthetic time to patient profile

### PR DESCRIPTION
**Pull request by DevChima**

### CODE REVIEW

**Review by erikh360 — COMMENTED** [review]
I would move it below the decision time as that is first.

a screenshot in the PR for frontend changes is also nice 🙂

**Comment by DevChima** [comment]
Alright. I'll do. Thanks

**Comment by DevChima** [comment]
hidden_anesthetic_time

**Comment by DevChima** [comment]
visible_anesthetic_time

**Review by erikh360 — APPROVED** [review]

**Pull request merged**
